-- ═══════════════════════════════════════════════════════
--  BankBot Admin Panel — MySQL Schema
--  Run this in MySQL Workbench or: mysql -u root -p < schema.sql
-- ═══════════════════════════════════════════════════════

CREATE DATABASE IF NOT EXISTS bankbot_admin CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bankbot_admin;

-- ── 1. Admin Users ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS admin_users (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at    DATETIME     DEFAULT CURRENT_TIMESTAMP
);

-- Default admin: username=admin, password=admin123
--   (bcrypt hash of "admin123" — generated by reset_admin.py)
INSERT INTO admin_users (username, password_hash) VALUES
('admin', '$2b$12$bshbxjqlwoNGnloV9.lF6u9bftnUtYdN.VXFo3DNAC9ZdPfoJy.b2')
ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash);

-- ── 2. User Query Logs ─────────────────────────────────
CREATE TABLE IF NOT EXISTS user_logs (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    message     TEXT         NOT NULL,
    intent      VARCHAR(100),
    confidence  FLOAT,
    response    TEXT,
    timestamp   DATETIME     DEFAULT CURRENT_TIMESTAMP
);

-- ── 3. FAQ ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS faq (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    question   TEXT    NOT NULL,
    answer     TEXT    NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Seed sample FAQs
INSERT INTO faq (question, answer) VALUES
('What are your working hours?',    'Branch hours: Mon–Fri 9:30 AM – 4:30 PM, Sat 9:30 AM – 1:30 PM. Call centre: 24/7.'),
('What is the minimum balance?',    'Savings Metro: Rs.10,000 | Semi-urban: Rs.5,000 | Rural: Rs.2,500 | Current: Rs.25,000.'),
('How do I block my card?',         'Call 1800-XXX-XXXX or use the chatbot by typing "block my card".'),
('What documents are needed for KYC?', 'Identity proof (Aadhaar/PAN/Passport) + Address proof (Aadhaar/Utility Bill).');

-- ── 4. Training Data ───────────────────────────────────
CREATE TABLE IF NOT EXISTS training_data (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    intent       VARCHAR(100) NOT NULL,
    example_text TEXT         NOT NULL,
    created_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Seed sample training examples
INSERT INTO training_data (intent, example_text) VALUES
('check_balance',       'What is my account balance?'),
('check_balance',       'Show me my savings balance'),
('transfer_money',      'Transfer 5000 rupees'),
('block_card',          'Block my debit card'),
('loan_inquiry',        'I want a home loan'),
('faq_working_hours',   'What are your working hours?');
